There was a small village with a beautiful environment. Everyone was living happy in the village . One morning the childrens with
have fun and laughter they reached the nearby school . A small child gets an admission to the school. That was his first day of 
attending the school . He was so excited to meet his new friends.....